### ISSUE TITLE
ReferenceError: clusterZookeeper is not defined

### ISSUE THREAD

**Issue by zhenghorse** [fwang7/node-red-contrib-kafka-node#2]
ReferenceError: clusterZookeeper is not defined
![image](https://cloud.githubusercontent.com/assets/897484/9571694/6843727c-4fd4-11e5-8abe-9944a7eb0072.png)
![image](https://cloud.githubusercontent.com/assets/897484/9571704/836a8d92-4fd4-11e5-8e6c-e06db2e02e53.png)

**Comment by fwang7** [comment]
Hi zhenghorse,
Did you have zookeeper installed or deployed? 

Thanks,
feng

**Comment by zhenghorse** [comment]
Thank you for your reply
zookeeper has started
![image](https://cloud.githubusercontent.com/assets/897484/9728006/91ec9fa4-5637-11e5-8717-8209a5552f71.png)
created kafka topic
![image](https://cloud.githubusercontent.com/assets/897484/9728013/a4bb43a6-5637-11e5-9a97-2f4e83c11d80.png)
kafka producer
![image](https://cloud.githubusercontent.com/assets/897484/9728027/c63cf8c6-5637-11e5-87bf-6904cc8e1dde.png)
kafka consumer
![image](https://cloud.githubusercontent.com/assets/897484/9728034/d5b72830-5637-11e5-950b-829c0d78ff65.png)
my node-red
![image](https://cloud.githubusercontent.com/assets/897484/9728049/e44352b6-5637-11e5-8e31-bcdc85612d6f.png)
zookeeper config
![image](https://cloud.githubusercontent.com/assets/897484/9728063/04841182-5638-11e5-8494-95d50a6e1e4d.png)

Thanks

**Comment by fwang7** [comment]
where did you deploy the NodeRED? on the same machine with kafka/zookeeper?

**Comment by zhenghorse** [comment]
on the same machine NodeRED and kafka/zookeeper
